name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Déclenche le workflow lors d'un push sur la branche main

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm # Changement pour npm

      - name: Install dependencies
        run: npm ci # Utilisation de npm ci pour installer les dépendances
      - name: Build website
        run: npm run build # Construction du site

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build # Chemin vers le dossier de build de Docusaurus

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write # Autorise le déploiement vers GitHub Pages
      id-token: write # Nécessaire pour vérifier la source du déploiement

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          deployment_branch: 'gh-pages'  # Déployer sur la branche gh-pages

