name: Test deployment

on:
  pull_request:
    branches:
      - main # Déclenche le workflow lors d'une demande de tirage sur la branche main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm # Changement pour npm

      - name: Install dependencies
        run: npm ci # Utilisation de npm ci pour installer les dépendances
      - name: Test build website
        run: npm run build # Teste la construction du site
